# config file for testing
# filename should be application.yml

app:
  project: hidevopsio
  name: bolt

logging:
  level: debug

dataSources:
- type: bolt # database type
  database: hi.db # database file path, e.g. /var/lib/data/hi.db or relative path hi.db
  mode: 0600 # database file permission
  timeout: 1 # connection timeout in second
